// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3iMG_Hc_zcYlwqgYgI5Ok0nw6n3pM7P4',
    appId: '1:933444481317:web:9f7fd616ff01edf72a6acc',
    messagingSenderId: '933444481317',
    projectId: 'notes-merged',
    authDomain: 'notes-merged.firebaseapp.com',
    storageBucket: 'notes-merged.appspot.com',
    measurementId: 'G-WGS1NF06TE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqmg3X_iUMz5iGpARLQEKiKlgf6zUB3i0',
    appId: '1:933444481317:android:5754c0135a54866c2a6acc',
    messagingSenderId: '933444481317',
    projectId: 'notes-merged',
    storageBucket: 'notes-merged.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIAUX3BxqfUD2f1NiaIesZlH9L7XRFi_c',
    appId: '1:933444481317:ios:456db70460fcc04d2a6acc',
    messagingSenderId: '933444481317',
    projectId: 'notes-merged',
    storageBucket: 'notes-merged.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIAUX3BxqfUD2f1NiaIesZlH9L7XRFi_c',
    appId: '1:933444481317:ios:456db70460fcc04d2a6acc',
    messagingSenderId: '933444481317',
    projectId: 'notes-merged',
    storageBucket: 'notes-merged.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3iMG_Hc_zcYlwqgYgI5Ok0nw6n3pM7P4',
    appId: '1:933444481317:web:6c47a85a52438e7e2a6acc',
    messagingSenderId: '933444481317',
    projectId: 'notes-merged',
    authDomain: 'notes-merged.firebaseapp.com',
    storageBucket: 'notes-merged.appspot.com',
    measurementId: 'G-L0EFGE73LE',
  );
}
